[General]
Color=#00000
KittyTransparincy=0.35
Version=0.0.1
Wallpaper=# Wallpaper location
WallpapersFolder=~/Pictures/Wallpapers
theme=Light# Lightor Dark

[Apps]
Browser=firefox
filemanager=dolphin
menu=ArtexDesktop --StartMenu
terminal=foot

[Hyprland]
active_border=0xff89b4fa
border_size=1
rounding=10

[Keybinds]
bind_ToggleFloting=Space
bind_browser=W
bind_close=C
bind_filemanager=E
bind_menu=R
bind_terminal=Q
main_mod=SUPER

[Version]
Version=0.2

[Wallpapers]
Wallpaper=/home/lulu/Pictures/Wallpapers/dva-overwatch-dark-background-anime-girl-3840x2160-5067.jpg
WallpapersFolder=/home/lulu/Pictures/Wallpapers
awww_transition=none

[theme]
colortheme=#0cb2ff
theme=Dark
