local function get_desktop_conf(group, key, default_val)
    local home = os.getenv("HOME") or ""
    local conf_path = home .. "/.config/Desktop.conf"
    local file = io.open(conf_path, "r")
    if not file then return default_val end

    local current_group = ""
    for line in file:lines() do
        -- Remove espaços nas pontas
        -- Em vez de reatribuir a mesma variável "line" constante:
        local trimmed_line = line:match("^%s*(.-)%s*$")

        -- Verifica se entrou em uma seção [NomeDaSecao]
        local g = line:match("^%[(.+)%]$")
        if g then
            current_group = g
        elseif current_group == group then
            -- Procura pela chave e pega o valor após o '='
            local k, v = line:match("^([^=]+)=(.*)$")
            if k and v then
                k = k:match("^%s*(.-)%s*$")
                v = v:match("^%s*(.-)%s*$")
                if k == key then
                    file:close()
                    return v
                end
            end
        end
    end
    file:close()
    return default_val
end

local conf_rounding    = tonumber(get_desktop_conf("Hyprland", "rounding", "10")) or 10
local conf_border_size = tonumber(get_desktop_conf("Hyprland", "border_size", "2")) or 2
local conf_active_col  = get_desktop_conf("Hyprland", "active_border", "0xffffffff")

hl.config({
    autogenerated = false,

    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = conf_border_size,

        col = {
            -- Passa a string no formato '0xff89b4fa' que é 100% válida no Hyprland
            active_border   = { colors = {conf_active_col, conf_active_col}, angle = 45 },
            inactive_border = { colors = {"rgba(0, 0, 0, 0)", "rgba(0, 0, 0, 0)"}, angle = 45},
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
    },

    decoration = {
        rounding = conf_rounding, -- Usando a variável lida do Desktop.conf
        rounding_power = 2,

        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = false,
            range        = 40,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 5,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },

    dwindle = {
        preserve_split = true, -- You probably want this
    },
    scrolling = {
        fullscreen_on_one_column = true,
    },
    master = {
        new_status = "master",
    },
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

--[[hl.config({
    decoration = {
        blur = {
            enabled = true, -- atenção ao 'd' no final (enabled)
            size = 8,
            passes = 3
        }
    }
})]]