-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- Dimitrof04 ~ Config, thanks for use :3
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

hl.config({ autogenerated = false }) -- remove this line to remove the warning

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})
-------------------
---- AUTOSTART ----
--------------------

-- Função para ler valores do arquivo ~/.config/Desktop.conf
local function get_desktop_conf(group, key, default_val)
    local home = os.getenv("HOME") or ""
    local conf_path = home .. "/.config/Desktop.conf"
    local file = io.open(conf_path, "r")
    if not file then return default_val end

    local current_group = ""
    for line in file:lines() do
        -- Remove espaços nas pontas
        -- Em vez de reatribuir a mesma variável "line" constante:
        local trimmed_line = line:match("^%s*(.-)%s*$")

        -- Verifica se entrou em uma seção [NomeDaSecao]
        local g = line:match("^%[(.+)%]$")
        if g then
            current_group = g
        elseif current_group == group then
            -- Procura pela chave e pega o valor após o '='
            local k, v = line:match("^([^=]+)=(.*)$")
            if k and v then
                k = k:match("^%s*(.-)%s*$")
                v = v:match("^%s*(.-)%s*$")
                if k == key then
                    file:close()
                    return v
                end
            end
        end
    end
    file:close()
    return default_val
end

local conf_rounding    = tonumber(get_desktop_conf("Hyprland", "rounding", "10")) or 10
local conf_border_size = tonumber(get_desktop_conf("Hyprland", "border_size", "2")) or 2
local conf_active_col  = get_desktop_conf("Hyprland", "active_border", "0xffffffff")

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("NetwokManager")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("chmod +x " .. MenuDesktop)
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
-- Configuring Window
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = conf_border_size,

        col = {
            -- Passa a string no formato '0xff89b4fa' que é 100% válida no Hyprland
            active_border   = { colors = {conf_active_col, conf_active_col}, angle = 45 },
            inactive_border = { colors = {"rgba(0, 0, 0, 0)", "rgba(0, 0, 0, 0)"}, angle = 45},
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "dwindle",
    },

    decoration = {
        rounding = conf_rounding, -- Usando a variável lida do Desktop.conf
        rounding_power = 2,

        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = false,
            range        = 40,
            render_power = 3,
            color        = 0xee1a1a1a,
        },

        blur = {
            enabled   = true,
            size      = 3,
            passes    = 1,
            vibrancy  = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },
})

local AandC = require("animationcurve") 
-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
    dwindle = {
        preserve_split = true, -- You probably want this
    },
    scrolling = {
        fullscreen_on_one_column = true,
    },
    master = {
        new_status = "master",
    },
})

----------------
----  MISC  ----
----------------

hl.config({
    misc = {
        force_default_wallpaper = -1,    -- Set to 0 or 1 to disable the anime mascot wallpapers
        disable_hyprland_logo   = false, -- If true disables the random hyprland logo / anime girl background. :(
    },
})


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = false,
        },
    },
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
    name        = "epic-mouse-v1",
    sensitivity = -0.5,
})

local Keybinds = require("Keybindings")

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
    -- Ignore maximize requests from all apps. You'll probably like this.
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

-- Hyprland-run windowrule
hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})