[General]
Color=#00000
KittyTransparincy=0.35
Version=0.0.1
Wallpaper=# Wallpaper location
WallpapersFolder=~/Pictures/Wallpapers
theme=Light# Lightor Dark

[Apps]
Browser=firefox
filemanager=dolphin
menu=ArtexDesktop --StartMenu
terminal=kitty

[Hyprland]
active_border=0xff89b4fa
border_size=1
rounding=10

[Keybinds]
bind_ToggleFloting=Space
bind_browser=W
bind_close=C
bind_filemanager=E
bind_menu=R
bind_terminal=Q
main_mod=SUPER

[Version]
Version=0.1

[Wallpapers]
Wallpaper=/home/lulu/Pictures/Wallpapers/anime2.jpg
WallpapersFolder=/home/lulu/Pictures/Wallpapers
awww_transition=fade

[theme]
colortheme=#26c5ff
theme=Light
