[General]
Color=#00000
KittyTransparincy=0.35
Version=0.0.1
Wallpaper=# Wallpaper location
WallpapersFolder=~/Pictures/Wallpapers
theme=Light# Lightor Dark

[Apps]
filemanager=dolphin
menu=hyprlauncher
terminal=kitty

[Hyprland]
active_border=0xffffffff
border_size=1
rounding=10

[Keybinds]
bind_close=C
bind_filemanager=E
bind_menu=R
bind_terminal=Q
main_mod=SUPER

[Version]
Version=0.0.1

[Wallpapers]
Wallpaper=/home/lulu/Pictures/Wallpapers/Meptl.png
WallpapersFolder=/home/lulu/Pictures/Wallpapers
awww_transition=random

[theme]
colortheme=#0cb6ff
theme=Dark
