# [theme]
theme = "Light" # "Light" or "Dark"
Color = "#00000"
# [Wallpapers]
Wallpaper = "" # Wallpaper location
WallpapersFolder = "~/Pictures/Wallpapers"
# [Version]
Version = 0.0.1
# Kitty
KittyTransparincy = 0.35